# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d2f1c1ed4f375b7473e07e09110170e451c20fab0b365ec2d6dc8f263c290be13e3c16125dcc2218fbfae8de6190cd39c8ced58cdabe06abb7d9da7493292ec

test:
  secret_key_base: d216adf43e1b4f4a5a4b0664c69cdea2f7e8bd369504dce84bbea4bb76587644d603d6f9076ab6de9b94b59700fca649daf7659807c33ac122aa27e1b8f86597

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
